String errorMessage(ErrorsTypes errorType) {
  return errorsMapping[errorType] ?? 'No Readable Error Message For This Error';
}

const Map<ErrorsTypes, String> errorsMapping = {
  ErrorsTypes.locationNotEnabled: 'لم يتم تحديد موقعك',
  ErrorsTypes.locationPermissionNotGranted: 'من فضلك قم بالسماح بخدمة الموقع',
  ErrorsTypes.noUserLoggedIn: 'لم يتم تسجيل الدخول',
  ErrorsTypes.loveError: 'حدث خطأ',
  ErrorsTypes.unknownError: 'خطأ غير معروف',
  ErrorsTypes.uploadPhoto: 'خطأ أثناء رفع الصورة',
  ErrorsTypes.fetchingUserPhoto: 'خطأ في تحميل صورة المستخدم',
  ErrorsTypes.errorGettingLocation: 'خطأ في تحديد الموقع',
  ErrorsTypes.errorPlacingOrder: 'خطأ في إضافة الطلبية',
  ErrorsTypes.errorGettingOrders: 'خطأ في تحميل الطلبيات',
  ErrorsTypes.errorLoadingProducts: 'خطأ في تحميل المنتجات',
  ErrorsTypes.errorGettingNextHomeProducts: 'خطأ في تحميل مزيد من المنتجات',
  ErrorsTypes.errorGettingLikedProducts: 'خطأ في معرفة اللايكات',
  ErrorsTypes.errorUpdatingState: 'خطأ في تحديث ال state',
  ErrorsTypes.errorUpdateLovesNumber: 'خطأ في تعديل عدد اللايكات',
  ErrorsTypes.errorFetchingStores: 'خطأ في تحميل المحلات',
  ErrorsTypes.errorSignUpStore: 'خطأ في تسجيل محل جديد',
  ErrorsTypes.errorGettingUserData: 'خطأ في تحميل معلومات المسخدم',
  ErrorsTypes.cantGoogleSignIn: 'لا يمكن استخدام تسجيل جوجل',
  ErrorsTypes.cantSignOut: 'لا يمكن تسجيل الخروج',
  ErrorsTypes.addingStoreTabError: 'خطأ في إنشاء قسم جديد',
  ErrorsTypes.errorAddingProductsToTab: 'خطأ في إضافة المنتجات',
  ErrorsTypes.errorRemovingProduct: 'خطأ في حذف المنتج',
  ErrorsTypes.errorDeletingOffer: 'خطأ في حذف العرض',
  ErrorsTypes.errorEditingProduct: 'خطأ في تعديل المنتج',
  ErrorsTypes.errorCreatingOffer: 'خطأ في إنشاء العرض',
  ErrorsTypes.errorCreatingAds: 'خطأ في إنشاء الاعلان',
  ErrorsTypes.errorLoadingAds: 'خطأ في تحميل الاعلانات',
};

enum ErrorsTypes {
  locationNotEnabled,
  locationPermissionNotGranted,
  noUserLoggedIn,
  loveError,
  unknownError,
  uploadPhoto,
  fetchingUserPhoto,
  errorGettingLocation,
  errorPlacingOrder,
  errorGettingOrders,
  errorLoadingProducts,
  errorGettingNextHomeProducts,
  errorGettingLikedProducts,
  errorUpdatingState,
  errorUpdateLovesNumber,
  errorFetchingStores,
  errorSignUpStore,
  errorGettingUserData,
  cantGoogleSignIn,
  cantSignOut,
  addingStoreTabError,
  errorAddingProductsToTab,
  errorRemovingProduct,
  errorDeletingOffer,
  errorEditingProduct,
  errorCreatingOffer,
  errorCreatingAds,
  errorLoadingAds,
}
