//? product model constants
String idString = 'idString';
String nameString = 'nameString';
String storeIdString = 'storeIdString';
String storeLogoString = 'storeLogoString';
String storeNameString = 'storeNameString';
String storeActiveOffersString = 'storeActiveOffersString';
String imagesPathString = 'imagesPathString';
String createdAtString = 'createdAtString';
String lovesNumberString = 'lovesNumberString';
String priceString = 'priceString';
String wishListIdString = 'wishListIdString';
String brandString = 'brandString';
String availableSizeString = 'availableSizeString';
String nOfCommentsString = 'nOfCommentsString';
String ratingString = 'ratingString';
String oldPriceString = 'oldPriceString';
String remainingNumberString = 'remainingNumberString';
String hasOfferString = 'hasOfferString';
String offerEndString = 'offerEndString';
String offerStartedString = 'offerStartedString';
String favoriteString = 'favoriteString';
String fullDescString = 'fullDescString';
String shortDescString = 'shortDescString';
String availableColorsString = 'availableColorsString';
String keyWordsString = 'keyWordsString';
String categoryString = 'categoryString';

//? brand model constants
String iconString = 'iconString';

//? store model constants
String logoImagePathString = 'logoImagePathString';
String coverImagePathString = 'coverImagePathString';
String followersString = 'followersString';
String descString = 'descString';
String offersString = 'offersString';
String locationString = 'locationString';
String distanceString = 'distanceString';
String creatorUserUIDString = 'creatorUserUIDString';

//? offer model constants
String titleString = 'titleString';
String endAtString = 'endAtString';
String activeString = 'activeString';
String productIdString = 'productIdString';

//? user model constants
String emailString = 'emailString';
String addressString = 'addressString';
String phoneString = 'phoneString';
String birthDateString = 'birthDateString';
String userGenderString = 'userGenderString';
String userRoleString = 'userRoleString';
String singUpString = 'singUpString';
String userProfilePhotoString = 'userProfilePhotoString';
String userNameString = 'userNameString';
