//? product model constants
String idString = 'idString';
String nameString = 'nameString';
String storeIdString = 'storeIdString';
String storeLogoString = 'storeLogoString';
String storeNameString = 'storeNameString';
String storeActiveOffersString = 'storeActiveOffersString';
String imagesPathString = 'imagesPathString';
String createdAtString = 'createdAtString';
String lovesNumberString = 'lovesNumberString';
String priceString = 'priceString';
String wishListIdString = 'wishListIdString';
String brandString = 'brandString';
String availableSizeString = 'availableSizeString';
String nOfCommentsString = 'nOfCommentsString';
String ratingString = 'ratingString';
String oldPriceString = 'oldPriceString';
String remainingNumberString = 'remainingNumberString';
String hasOfferString = 'hasOfferString';
String offerEndString = 'offerEndString';
String favoriteString = 'favoriteString';
String fullDescString = 'fullDescString';
String shortDescString = 'shortDescString';
String availableColorsString = 'availableColorsString';

//? brand model constants
String iconString = 'iconString';
